fragment BountyFrag on Bounty {
  id
  bountyAddress
  startDate
  deadline
  business {
    id
    bountiesCompleted
  }
  influencers {
    id
    bountiesCompleted
  }
  availablePayoutDate
  objective
  maxJackpotRewardAmount
  jackpotTargetAmount
  simplePostDuration
  depositedBalance
  ongoing
  bountyType
  maxParticipants
  maxWinners
  maxJackpotRewardAmount
  endedWithRefund
  businessRefundAmount
}

query bountyQuery($id: String!) {
  bounties(where: { id: $id }) {
    ...BountyFrag
  }
}
