fragment BountyFrag on Bounty {
  id
  bountyAddress
  startDate
  deadline
  business {
    id
  }
  availablePayoutDate
  objective
  maxJackpotRewardAmount
  jackpotTargetAmount
  simplePostDuration
  depositedBalance
  ongoing
  bountyType
  maxJackpotRewardAmount
  # endedWithRefund
}

query bountyQuery($id: String!) {
  bounties(where: { id: $id }) {
    ...BountyFrag
  }
}
