fragment CampaignFrag on Campaign {
    id
    startDate
    deadline
    business {
      id
    }
    influencer {
      id
    }
    objective
    outstandingPayments
    jackpotTargetAmount
    simplePostDuration
    incrementalTargetAmount
    depositedBalance
    ongoing
}

# query campaignQuery($where: Campaign_Filter!) {
#     campaigns(where: $where)
# }

