fragment DealFrag on Campaign {
  id
  campaignAddress
  startDate
  deadline
  business {
    id
  }
  influencer {
    id
  }
  objective
  businessRefundAmount
  outstandingPayments
  jackpotTargetAmount
  simplePostDuration
  incrementalTargetAmount
  depositedBalance
  ongoing
  jackpotObjectiveReached
  incrementalRewardAmount
  jackpotRewardAmount
  endedWithRefund
}

query dealQuery($id: String!) {
  campaigns(where: { id: $id }) {
    ...DealFrag
  }
}
