fragment CampaignFrag on Campaign {
  id
  startDate
  deadline
  business {
    id
  }
  influencer {
    id
  }
  objective
  outstandingPayments
  jackpotTargetAmount
  simplePostDuration
  incrementalTargetAmount
  depositedBalance
  ongoing
  incrementalRewardAmount
  jackpotRewardAmount
}
query GET_ALL_CAMPAIGNS_FOR_BUSINESS_QUERY($id: String!) {
  campaigns(where: { business: $id }) {
    ...CampaignFrag
  }
}
query GET_ALL_CAMPAIGNS_FOR_INFLUENCER_QUERY($id: String!) {
  campaigns(where: { influencer: $id }) {
    ...CampaignFrag
  }
}
# query GET_ALL_CAMPAIGNS_FOR_INFLUENCER_QUERY($id: String!) {
#   influencers(where: {id: $id}){
#     id
#     campaigns{
#       ...CampaignFrag
#     }
#   }
# }
