fragment BountyFrag on Bounty {
  id
  bountyAddress
  startDate
  deadline
  business {
    id
    bountiesCompleted
  }
  influencers {
    id
    bountiesCompleted
  }
  availablePayoutDate
  objective
  maxJackpotRewardAmount
  jackpotTargetAmount
  simplePostDuration
  depositedBalance
  ongoing
  bountyType
  maxParticipants
  maxWinners
  maxJackpotRewardAmount
  outstandingPayments
}

query GET_ALL_CAMPAIGNS_FOR_BENEFICIARY_QUERY($id: String!) {
  campaigns(where: { business: $id }) {
    ...CampaignFrag
  }
}
query GET_ALL_CAMPAIGNS_FOR_GRANTOR_QUERY($id: String!) {
  campaigns(where: { influencer: $id }) {
    ...CampaignFrag
  }
}
